INTER/INTER/Controllers/ClasserController.cs
using INTER.DataModel;
using INTER.Service;
using Microsoft.AspNetCore.Mvc;

namespace INTER.Controllers
{
    public class ClasserController : Controller
    {

        private readonly IClassService _ClassService;

        public ClasserController(IClassService classService)
        {
            _ClassService = classService;
        }
        /// <summary>
        /// show class
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Show()
        {
            var classer = _ClassService.Classers();
            return
            View(classer);
        }
        /// <summary>
        ///  view create class
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult CreateClass()
        {
            return View();
        }
        
        /// <summary>
        ///  funtion  create class
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult CreateClass(CreateClasserModel createClass)
        {
            _ClassService.CreaterClass(createClass);
            return Redirect("/Classer/Show");
        }
        /// <summary>
        /// delete a Entity Classer for Id 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
       
        public IActionResult DeleteClass(int id)
        {
            _ClassService.Delete(id);
            return Redirect("/Classer/Show");
        }
        
        /// <summary>
        /// view Update
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Update(int id, string name)
        {
            _ClassService.GetById(id);
            return View();
        }
        
        /// <summary>
        ///  Update claseer
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Update(CreateClasserModel model)
        {
            _ClassService.Update(model);
            return Redirect("/Classer/Show");
        }
        
    }
}

INTER/INTER/Views/Classer/CreateClass.cshtml
@model INTER.DataModel.CreateClasserModel

@{
    ViewBag.Title = "title";
    Layout = "_Admin";
}

<div class="container-fluid" >
    <div class="row">
        <div class="col-sm-12">
            
            <table class="table table-bordered table-hover">
                <form asp-controller="Classer" asp-action="CreateClass" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Email" asp-for="ClassName">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" asp-for="ClassMember">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block">Create</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
            </table>
        </div>
       
    </div>
</div>

INTER/INTER/Views/Classer/Show.cshtml
@model IEnumerable<INTER.DataAccess.Classer>

@{
    ViewBag.Title = "title";
    Layout = "_Admin";
}


<div class="container-fluid">
    <div class="row">
        <a class="btn btn-primary " asp-controller="Classer" asp-action="CreateClass">Create Class</a>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">       
                <tr style="background-color: darkgrey">
                    <td >ID</td>
                    <td >Class Name</td>
                    <td >Class Member</td>
                    <td style="text-align: center">Update - Delete</td>
                </tr>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td >@item.Id</td>
                        <td>@item.ClassName</td>
                        <td>@item.ClassMember</td>
                        <td style="text-align: center">
                            <a class="btn btn-primary " asp-route-name="@item.ClassName" asp-controller="Classer" asp-action="Update" asp-route-id="@item.Id"  >Update</a>
                            <a class="btn btn-primary " asp-route-id="@item.Id" asp-action="DeleteClass" asp-controller="Classer">Delete</a>
                        </td>
                    </tr>
                }
                </tbody>
                </thead>

            </table>
        </div>

    </div>
</div>


   

INTER/INTER/Views/Classer/Update.cshtml
@model INTER.DataModel.CreateClasserModel
@{
    ViewBag.Title = "title";
    Layout = "_Admin";
}

<div class="container-fluid" >
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-bordered table-hover">
                <form  asp-controller ="Classer" asp-action ="Update" method="post" >
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Email" asp-for="ClassName"   >
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">  
                        <input type="password" class="form-control" placeholder="Password" asp-for="ClassMember">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block"  >Update</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
            </table>
        </div>
       
    </div>
</div>